# Exercises for Numpy

1- Import numpy as `np` and print the version number. 

In [108]:
# Your code here
import warnings
warnings.filterwarnings('ignore')

In [109]:
import numpy as np
np.__version__

'1.19.2'

2- Create a 1D array of numbers from 0 to 9 
- Desired output:
```Python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [2]:
# Your code here
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Create a 3×3 numpy array of all True’s
- Desired output:
```Python
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)
```

In [7]:
# Your code here
a =np.ones((3, 3), dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4- Extract all odd numbers from `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([1, 3, 5, 7, 9])
```

In [11]:
# Your code here
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5- Replace all odd numbers in arr with -1
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [13]:
# Your code here
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range (len(arr)):
    if(arr[i]%2 == 1):
        arr[i] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6- Replace all odd numbers in arr with -1 without changing `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [19]:
# Your code here
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
h = arr.copy()
for i in range (len(h)):
    if(h[i]%2 == 1):
        h[i] = -1
print(h)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


7- Convert a 1D array to a 2D array with 2 rows
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [20]:
# Your code here
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8- Stack arrays `a` and `b` vertically 
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [21]:
# Your code here
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9- Stack the arrays a and b horizontally.
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [22]:
# Your code here
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10- Get the common items between `a` and `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([2, 4])
```

In [24]:
# Your code here
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.intersect1d(a, b) # intersect1d function helps in finding common elements of 1-D array. 

array([5])

11- From array `a` remove all items present in array `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([1,2,3,4])
```

In [36]:
# Your code here
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
present_element = np.intersect1d(a, b)  #Extract the element that is present in both a and b
result = np.where(a ==present_element[0]) #Extract the index of the element present in a and b 
np.delete(a, result[0]) #Remove the element from a 

array([1, 2, 3, 4])

12- Get the positions where elements of `a` and `b` match
- Input
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
- Desired output:
```Python
#> (array([1, 3, 5, 7]),)
```

In [42]:
# Your code here
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.array([])
for i in range(len(a)):
    if(a[i] == b[i]):
        c = np.append(c,i)
c

array([1., 3., 5., 7.])

13- Get all items between 5 and 10 from `a`
- Input
```Python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
- Desired output:
```Python
#> (array([6, 9, 10]),)
```

In [49]:
# Your code here
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<=10)]

array([ 6,  9, 10])

14- Convert the function `maxx` that works on two scalars, to work on two arrays
- Input
```Python
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
```Python
maxx(1, 5)
#> 5
```

- Desired output:

```Python
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [51]:
# Your code here
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def pair_max(a, b):
    c = np.array([])
    for i in range(len(a)):
        if(a[i] >= b[i]):
            c = np.append(c,a[i])
        else:
            c = np.append(c,b[i])
    return(c)
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

15- Reverse the rows of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]])
```

In [60]:
# Your code here
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

16- Reverse the columns of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]]
```

In [69]:
# Your code here
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

17- Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10 (use `np.random.seed()` to generate the same random output).
- Desired output: (for seed number equal 10)
```Python
#> array([[6.15037787, 9.68381843, 5.81660184],
#>       [6.33607158, 8.89081653, 9.19812181],
#>       [6.03061665, 5.87761494, 6.72743551],
#>       [7.54088093, 5.13145815, 6.41366737],
#>       [5.77872881, 7.58390137, 5.18263144]])
```

In [73]:
# Your code here
np.random.seed(10)
5 * np.random.rand(5,3) + 5

array([[8.85660322, 5.10375975, 8.16824117],
       [8.74401941, 7.49253506, 6.12398323],
       [5.99031432, 8.80265356, 5.84555418],
       [5.44169907, 8.42679909, 9.76696673],
       [5.01974133, 7.56096132, 9.06310481]])

18- Print or show only 3 decimal places of the numpy array `rand_arr`
- Input
```Python
rand_arr = np.random.random((5,3))
```
- Desired output:
```Python
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])
```

In [95]:
# Your code here
rand_arr = np.random.random((5,3))
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
rand_arr[:4]

array([[ 0.613,  0.722,  0.292],
       [ 0.918,  0.715,  0.543],
       [ 0.142,  0.373,  0.674],
       [ 0.442,  0.434,  0.618]])

19- Pretty print `rand_arr` by suppressing the scientific notation (like 1e10) 
- Input

```Python
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```
```Python
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

- Desired output:
```python
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])
```

In [99]:
# Your code here
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress = True)
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

20- Limit the number of items printed in python numpy array a to a maximum of 6 elements.
- Input:
```Python
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```
- Desired output:
```Python
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [102]:
# Your code here
a = np.arange(15)
np.set_printoptions(threshold = 6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

21- Convert the 1D iris to 2D array iris_2d by omitting the species text field.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```
- Desired output:
```Python
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])
```

In [118]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

22- Find the mean, median, standard deviation of iris's sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(mean, median, sd)
#> 5.84333333333 5.8 0.825301291785
```

In [122]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean, median, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, median, sd)

5.843333333333334 5.8 0.8253012917851409


23- Create a normalized form of iris‘s sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```

In [130]:
# Your code here

#Setting parameters for printing
np.set_printoptions(threshold = 1000)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

#Generating a normalized iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
max_sepal = sepallength.max()
min_sepal = sepallength.min()
normalized_sepal = (sepallength - min_sepal)/(max_sepal - min_sepal)
print(normalized_sepal)

[ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
  0.306  0.139  0.139  0.000  0.417  0.389  0.306  0.222  0.389  0.222
  0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.250  0.250  0.111
  0.139  0.306  0.250  0.333  0.167  0.194  0.333  0.167  0.028  0.222
  0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
  0.750  0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.250
  0.194  0.444  0.472  0.500  0.361  0.667  0.361  0.417  0.528  0.361
  0.444  0.500  0.556  0.500  0.583  0.639  0.694  0.667  0.472  0.389
  0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
  0.333  0.500  0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
  0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
  0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
  0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.500  0.583  0.806
  0.861  1.000  0.583  0.556  0.500  0.944  0.556  0.583  0.472  0.722
  0.66

24- Find the number and position of missing values in iris_2d‘s sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```
- Desired output:
```Python
#> Number of missing values: 
...
#> Position of missing values: 
...
```

In [138]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
number = np.isnan(iris_2d[:, 0]).sum()
position = np.where(np.isnan(iris_2d[:, 0]))
print("Number of missing values: \n",number)
print("Position of missing values: \n",position)

[ 5.100  2.100  4.900  2.200  2.900  1.400  1.500  4.500  4.900  2.300
  4.100  0.200  6.300  3.100  3.000  4.600  6.100  1.900  4.000  0.400]
Number of missing values: 
 4
Position of missing values: 
 (array([47, 49, 87, 89]),)


25- Select the rows of iris_2d that does not have any nan value
- Input:
```Python
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [144]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#Selecting all the rows that does not have nan values 
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[ 5.100,  3.500,  1.400,  0.200],
       [ 4.900,  3.000,  1.400,  0.200],
       [ 4.700,  3.200,  1.300,  0.200],
       [ 4.600,  3.100,  1.500,  0.200],
       [ 5.000,  3.600,  1.400,  0.200]])

26- Replace all ccurrences of `nan` with 0 in numpy array
- Input
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [147]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
#Replacing nan values with 0
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:6]

array([[ 5.100,  3.500,  1.400,  0.200],
       [ 4.900,  3.000,  1.400,  0.200],
       [ 4.700,  3.200,  1.300,  0.200],
       [ 4.600,  3.100,  1.500,  0.200],
       [ 5.000,  3.600,  1.400,  0.200],
       [ 5.400,  3.900,  1.700,  0.400]])

27- Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> 'small'
- 3-5 –> 'medium'
- '>=5 –> 'large'
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
- Desired output:
```Python
petal_length_cat[:4]
#> ['small', 'small', 'small', 'small']
```

In [151]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#we use np.digitize which returns the indices of the bins to which each value in input array belongs.
#Our input array is the 3rd column of iris data: iris[:, 2]
#Our bins array is : [0, 3, 5, 10]
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

#After getting the indices of bins, we assign to each indice a value (text)
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}

#We then get the category of each element in the bins array 
petal_length_cat = [label_map[x] for x in petal_length_bin]
petal_length_cat

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

28- Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
#> 50
```

In [154]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

#We first take the 4th column which is iris[:, 3], we turn its values to float to compare them with 1.0 
#We get an array of the True or False valuing the condition given
(iris[:, 3].astype(float) > 1.0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [155]:
#We then take the positions where the condition returns True
np.argwhere(iris[:, 3].astype(float) > 1.0)

array([[ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 58],
       [ 59],
       [ 61],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 68],
       [ 69],
       [ 70],
       [ 71],
       [ 72],
       [ 73],
       [ 74],
       [ 75],
       [ 76],
       [ 77],
       [ 78],
       [ 80],
       [ 82],
       [ 83],
       [ 84],
       [ 85],
       [ 86],
       [ 87],
       [ 88],
       [ 89],
       [ 90],
       [ 91],
       [ 92],
       [ 94],
       [ 95],
       [ 96],
       [ 97],
       [ 98],
       [ 99],
       [100],
       [101],
       [102],
       [103],
       [104],
       [105],
       [106],
       [107],
       [108],
       [109],
       [110],
       [111],
       [112],
       [113],
       [114],
       [115],
       [116],
       [117],
       [118],
       [119],
       [120],
       [121],
       [122],
       [123],
       [124],
       [125],
       [126],
       [127],
      

In [156]:
#We finally get the first element of the array that corresponds to the first occurence
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

29- From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 
- Input:
```Python
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```
- Desired output:
```Python
#> [ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
#>   11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```

In [158]:
# Your code here
np.random.seed(100)
a = np.random.uniform(1,50, 20)
#Operation 1 : Using np.where(), we first take the array a and replace elements that are greater than 30 with 30
#we take the output of the array resulting from operation1 and we replace its elements that are less than 10 with 10
np.where(a < 10, 10, np.where(a > 30, 30, a))

array([ 27.627,  14.640,  21.801,  30.000,  10.000,  10.000,  30.000,
        30.000,  10.000,  29.180,  30.000,  11.251,  10.081,  10.000,
        11.765,  30.000,  30.000,  10.000,  30.000,  14.430])

30- Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’
- Input
```Python
from io import BytesIO
from PIL import Image
import PIL, requests
```

In [160]:
# Your code here
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Convert to numpy array
arr = np.asarray(I)
arr

array([[[  9,  72, 125],
        [  9,  72, 125],
        [  9,  72, 125],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [  9,  72, 125],
        [ 10,  73, 126],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [ 10,  73, 126],
        [ 10,  73, 126],
        ...,
        [ 44, 105, 150],
        [ 45, 106, 151],
        [ 45, 106, 151]],

       ...,

       [[ 21,  41,  50],
        [ 29,  51,  64],
        [ 28,  54,  69],
        ...,
        [ 27,  58,  79],
        [ 22,  53,  74],
        [ 19,  47,  69]],

       [[ 27,  51,  63],
        [ 29,  55,  68],
        [ 27,  56,  72],
        ...,
        [ 33,  70,  97],
        [ 27,  64,  91],
        [ 22,  57,  85]],

       [[ 18,  45,  56],
        [ 20,  48,  62],
        [ 21,  52,  70],
        ...,
        [ 15,  51,  77],
        [ 12,  48,  74],
        [ 11,  45,  72]]